blank_issues_enabled: false
contact_links:
  - name: Feedback or requests
    url:  https://github.com/microsoft/vscode/issues/new/choose
    about: Please make any icon requests in the official VS Code repo
